// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUB_8fwywlEJgXoR1mpRvCTCNJYxZkn-M',
    appId: '1:281102717393:web:19960991e36731c21d90f0',
    messagingSenderId: '281102717393',
    projectId: 'mini-wheelz',
    authDomain: 'mini-wheelz.firebaseapp.com',
    storageBucket: 'mini-wheelz.firebasestorage.app',
    measurementId: 'G-1CM2VW6XCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfaNwBnn0bZHSipMHBg5B4IpENaseE2vY',
    appId: '1:281102717393:android:697cbcb31b17fb6c1d90f0',
    messagingSenderId: '281102717393',
    projectId: 'mini-wheelz',
    storageBucket: 'mini-wheelz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEcdv-o9bFvcoQC_Z5P9mZAIWz7DvhWrs',
    appId: '1:281102717393:ios:670300cfc59ffeed1d90f0',
    messagingSenderId: '281102717393',
    projectId: 'mini-wheelz',
    storageBucket: 'mini-wheelz.firebasestorage.app',
    iosBundleId: 'com.example.miniWheelz',
  );
}
